

export const postConstants = {
    FETCH_POSTS_REQUEST: 'FETCH_POSTS_REQUEST',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
    REMOVE_POST: 'REMOVE_POST',
    FETCH_NEW_ROW_SUCCESS: 'FETCH_NEW_ROW_SUCCESS',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE'
}